#!/bin/sh
echo "PRE PUSH"

echo "--- Linting css ---"
pnpm lint:css || exit 1

echo "--- Linting js ---"
pnpm lint:check || exit 1

echo "--- Running tests ---"
pnpm test:run || exit 1

echo "--- Validating Build Consistency ---"
pnpm build || exit 1