#!/bin/sh
echo "Running pre-push checks..."

echo "--- Linting css ---"
pnpm lint:css || exit 1

echo "--- Linting js ---"
pnpm lint:check || exit 1

echo "--- Running tests ---"
pnpm test:related || exit 1

echo "--- Validating Build Consistency ---"
pnpm build || exit 1