name: 'Setup Node + pnpm'
description: 'Unified setup for pnpm with multi-layer caching'

env:
    CACHE_PREFIX: ci
    CACHE_VERSION: v1


inputs:
  node-version:
    description: 'Node version'
    default: '24'
  install:
    description: 'Run pnpm install?'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v5
      with:
        version: 9

    - name: Set Cache Variables
      shell: bash
      run: |
        PREFIX=$([ "$ACT" = "true" ] && echo "act" || echo "ci")
        echo "CACHE_PREFIX=${PREFIX}-v1" >> $GITHUB_ENV
        echo "VITE_CACHE_DIR=./cache/vite_cache" >> $GITHUB_ENV
        echo "VITEST_CACHE_DIR=./cache/vitest_cache" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    # Global pnpm Store Cache
    - name: Get pnpm store path
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-${{ runner.os }}-pnpm-store-


    # Vite/Vitest Cache
    - uses: actions/cache@v4
      if: github.event.pull_request.head.repo.fork == false
      with:
        path: |
          path: |
          ${{ env.VITE_CACHE_DIR }}
          ${{ env.VITEST_CACHE_DIR }}
        key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-${{ runner.os }}-build-

    # Playwright cache
    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-${{ runner.os }}-playwright-

    # Prefetch
    - name: Prefetch deps
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm fetch

    # Install
    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      env:
        VITE_CACHE_DIR: ${{ env.VITE_CACHE_DIR }}
        VITEST_CACHE_DIR: ${{ env.VITEST_CACHE_DIR }}

    - name: Fix permissions
      shell: bash
      run: |
        chmod -R u+rwX .
