name: CI, CHANGES

on:
  workflow_call:
    outputs:
      app:
        description: 'App changes detected'
        value: ${{ jobs.changes.outputs.app }}
      docs:
        description: 'Docs changes detected'
        value: ${{ jobs.changes.outputs.docs }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      docs: ${{ steps.filter.outputs.docs }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fix git remote for act
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: main
          filters: |
            app:
              - 'src/**'
              - 'index.html'
              - 'vite.config.*'
              - 'package.json'
              - 'pnpm-lock.yaml' 
              - '.github/workflows/**'

            docs:
              - 'src/**'
              - 'README.md'
              - 'docs/**'
              - '*doc*.json' # Matches jsdoc.json, typedoc.json, etc.
              - 'tsconfig*.json'
