name: CI, DEPLOY

on:
  workflow_call:
    outputs:
      result:
        value: ${{ jobs.deploy.result }}

env:
  HUSKY: 0

# -----------------------------------
# DEPLOY APP
# -----------------------------------
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Download build from release job
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

      - name: Debug files
        run: |
          ls -la
          ls -la dist

      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name == 'develop' && 'develop' || '' }}
          keep_files: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
