name: 'PR'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  security-events: write
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-meta:
    uses: ./.github/workflows/pr-updater.yml

  preview:
    uses: ./.github/workflows/pr-preview.yml
