name: 'CI, SBOM GENERATOR'

permissions:
  contents: write
  id-token: write
  attestations: write
  security-events: write

on:
  workflow_call:
    outputs:
      generate-sbom:
        value: ${{ jobs.generate-sbom.result }}

env:
  HUSKY: 0

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6

      - name: Install Tools
        run: bash .github/scripts/security.sh install

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate Accurate SBOM
        run: bash .github/scripts/security.sh sbom

      - name: Attest SBOM
        if: env.ACT != 'true'
        uses: actions/attest-sbom@v2
        with:
          sbom-path: 'bom.json'
          subject-path: 'build-v${{ steps.semantic.outputs.new_release_version }}.zip'

      - name: Upload SBOM Artifact
        if: always() && env.ACT != 'true'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7
        with:
          name: software-bill-of-materials
          path: bom.json
